### ISSUE TITLE
Scripture should be cached for 1 day

### ISSUE THREAD

**Issue by calvinf** [ceaseless-prayer/CeaselessAndroid#1]
Currently, the app is not caching the verse.  It should cache the verse for 1 day before grabbing a new one.

**Comment by uberx** [comment]
Scripture, image URL, and list of people to pray for are all cached for a day now.
Commits that address this:
https://github.com/ceaseless-prayer/CeaselessAndroid/commit/3994318353025970e3939828e27c805ce2a00a82
https://github.com/ceaseless-prayer/CeaselessAndroid/commit/71ea67df1ee19506ce005dde7f2ec7f0d2c8f342
