### ISSUE TITLE
As a user I want to contact the developers to give feedback 

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#10]
Add a contact us function. Basically a blank e-mail to ceaseless@theotech.org with a Subject: Ceaseless for Android Feedback

**Comment by chrislim** [comment]
If we want to include info for twitter and facebook:

twitter.com/ceaselessprayer
www.facebook.com/ceaselesspraying
ceaselessprayer.com

**Comment by calvinf** [comment]
@chrislim or @nylim11, can you review the updated Contact Us view?

**Comment by calvinf** [comment]
**Screenshot**

Note: I believe the blue triangles in the corner of the images are from the Picasso library for debugging purposes.

![Contact Us View screenshot](https://cloud.githubusercontent.com/assets/40245/10409672/8fa69fbe-6ede-11e5-8f95-b31cc0076fa9.png)

**Comment by chrislim** [comment]
Can the URL used for FB&Twitter be of the kind that FB/Twitter can capture so users can choose to open in app? 

Copy adjustments:
If you have any questions or feedback about Ceaseless, we'd love to hear from you.
[Send us an email]

You can also connect with us on social media.
[FB] [TW]

Visit us on the web:
ceaselessprayer.com

**Comment by calvinf** [comment]
![updated contact us view](https://cloud.githubusercontent.com/assets/40245/10414056/5cd58cf6-6f76-11e5-83cf-2c91c07d7130.png)

The twitter link offered to open in the Twitter app.  The FB link does not.  I can check into this more later, but I'd like to call this initial task done.

**Comment by calvinf** [comment]
Resolved by 3cf979768df80b136beaff90b815bbeab73789de.  Updates to Facebook intent handling can be made separately.
