### ISSUE TITLE
Suggestion: Create an organization for ceaseless-prayer

### ISSUE THREAD

**Issue by joejoe2016** [ceaseless-prayer/CeaselessAndroid#118]
Hi,
I've seen that my pull request is still open - perhaps because nobody had the time to accept it.

So my suggestion is to create an organization for the ceaseless-prayer app and to have several users as maintainers of the project with write access to the different repos.
see eg. https://opensource.guide/leadership-and-governance/
I think that the project could only benefit from it.

What do you think?
joejoe2016

**Comment by chrislim** [comment]
This is a fantastic idea. I have set up an organization, but we have not setup a more formal governance structure. In the short term, I can give you write access so you can be a part of this. Let me check out the PRs.

**Comment by chrislim** [comment]
@joejoe2016  I've just added you to the organization.

**Comment by joejoe2016** [comment]
Thank you very much.
