### ISSUE TITLE
As a product owner I want to know the usage of my application so I can improve and promote it

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#14]
We need to integrate either with Google Analytics or Crashalytics or some other platform so we track user interactions and performance of our application.

**Comment by ajma** [comment]
do you want specific events? or just general metrics?

**Comment by chrislim** [comment]
I've asked Natasha to get the list from google analytics. Besides general metrics, we need things like number of people prayed for, favorited contacts, capture an event when a user adds a note, sends a message, sends an invite, favorites a contact, adds a contact in app, shares a scripture, shares a note, taps on help, submits feedback.

**Comment by chrislim** [comment]
Each screen of the app is now tracked in Google Analytics. Next step is to track actions users take.

**Comment by chrislim** [comment]
All basic analytics have now been added. We will want more ongoing, but I'm closing this ticket for now because the bar for the milestone has been reached.
