### ISSUE TITLE
As a user I want to see how many consecutive days I've prayed for others so that I have a sense of progress

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#15]

**Comment by ceasingone** [comment]
I'd also like to see more specific stats, like how much time I spent praying or how much time per person.

**Comment by chrislim** [comment]
This is not the same as consecutive days, nor do we have the additional metrics you mentioned yet, but this commit: 035ca6d adds a Day counter to the progress card, which in part meets the spirit of this ticket.

**Comment by nylim11** [comment]
Closing this ticket as consecutive days was implemented, the prayer stats idea is in #94
