### ISSUE TITLE
As a user I want to be able to use Ceaseless in other languages than English

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#16]
For this milestone, we need to support localization into:
- English
- Mandarin Chinese (Simplified)
- Bahasa Indonesia
- Hindi
- Spanish

**Comment by ajma** [comment]
who's gonna get us translations?

**Comment by chrislim** [comment]
For the developers, the only task here is to ensure all strings are localizable and in a strings.xml file. I can work on getting translations independently and then we ship with whatever we have available at milestone time.

**Comment by calvinf** [comment]
https://developer.android.com/distribute/tools/localization-checklist.html#gp-trans

**Comment by chrislim** [comment]
Strings are localizable. For now we have English, Japanese and Indonesian. Closing this issue for now.
