### ISSUE TITLE
Google Play Store Listing

### ISSUE THREAD

**Issue by ajma** [ceaseless-prayer/CeaselessAndroid#17]
Need the following:

# Required:
* Title (30 chars)
* Short description (80 chars)
* Full description (4000 chars)
* 2-8 screenshots (jpeg or png)
* Feature Graphic (1024x500 jpeg or png)
* Privacy policy link

# Optional:
* Promo Graphic (180x120 jpg or png)
* Promo Video (youtube link)

**Comment by chrislim** [comment]
We're working on this now.

**Comment by chrislim** [comment]
This has been created.
