### ISSUE TITLE
Use new permissions model for requesting contacts

### ISSUE THREAD

**Issue by ajma** [ceaseless-prayer/CeaselessAndroid#19]
https://developer.android.com/training/permissions/requesting.html

Contacts is the permission will most likely not install an app. We should use the new permissions model to ask at the time we need it rather than on install.

**Comment by chrislim** [comment]
This is a good idea. Also, in the user onboarding flow, we can describe why we need contacts permission and ask the user for it then.

**Comment by uberx** [comment]
Fixed by https://github.com/ceaseless-prayer/CeaselessAndroid/commit/db1c81293b64d2ca040dfb85619dbb52a32d2c56
