### ISSUE TITLE
App crashes if no contacts exist on phone

### ISSUE THREAD

**Issue by calvinf** [ceaseless-prayer/CeaselessAndroid#2]
Currently, the app crashes with an "indexOutOfBounds" exception of a phone contains no contacts.  Emulators don't have contacts by default, and new phones may not either.

**Comment by uberx** [comment]
This is fixed by https://github.com/ceaseless-prayer/CeaselessAndroid/commit/8cc6702ba134cfb6b0613fba00aca7c8fa566368, right?

**Comment by chrislim** [comment]
Yes that fixes it.
