### ISSUE TITLE
Use high res version of Ceaseless logo in menu

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#20]
I noticed the logo above the menu is a bit blurry. Please use a variant of this high res version. 
![ceaseless-dove-logo](https://cloud.githubusercontent.com/assets/469630/10412729/e23f5e54-6f43-11e5-9b89-23b301a50b5d.png)

**Comment by chrislim** [comment]
It is transparent background and white text, so may be hard to see until you download it :)

**Comment by uberx** [comment]
https://github.com/ceaseless-prayer/CeaselessAndroid/commit/c1ddb7d8e0fccbc3c476edf120115de14aa5533a
