### ISSUE TITLE
Notifications should fire only at the time user specifies in preferences

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#21]
Right now notifications go off seemingly randomly, we need to ensure it goes off at the time the user sets in the settings.

**Comment by jbprobert** [comment]
I'm going to make a change to how the notification is set so it doesn't do a day delay. I pulled the notification code from examples on stackoverflow, so I'll look at the AlarmManager docs to see if I'm doing something wrong.

**Comment by chrislim** [comment]
I think there are two thing we need to do:
1. Ensure the alarm goes off when they specify.
2. Ensure the alarm is set when the phone reboots. http://stackoverflow.com/questions/4459058/alarm-manager-example
3. Get permissions for local notifications with the new permissions model and at the right time in the user flow.

**Comment by chrislim** [comment]
1 and 2 are resolved in 4b34df
local notifications permissions are still happening the usual way.

**Comment by chrislim** [comment]
Oddly enough I'm still getting notifications randomly appearing throughout the day. I looked a little into the preferences to see if that may have been the problem. Looking into if I'm setting the alarm wrong too...

**Comment by jbprobert** [comment]
I had one job

**Comment by chrislim** [comment]
We're still seeing some problems here:
1. You have to view the settings and save them for the initial alarm to be installed. 
2. The first alarm works alright
3. Clicking on the notification runs something that schedules a new alarm
4. The alarms start coming in more frequently after that.

**Comment by chrislim** [comment]
When dump the alarms in the system when my app is making too many notifications, this is what I see:
<code>
$ adb shell dumpsys alarm | grep ceaseless
  RTC_WAKEUP #8: Alarm{14a9e19d type 0 when 1446519000081 org.theotech.ceaselessandroid}
    tag=*walarm*:org.theotech.ceaselessandroid/.notification.DailyNotificationService
    operation=PendingIntent{2b811612: PendingIntentRecord{2422a08a org.theotech.ceaselessandroid startService}}
  u0a276:org.theotech.ceaselessandroid +75ms running, 2 wakeups:
    +75ms 2 wakes 2 alarms: *walarm*:org.theotech.ceaselessandroid/.notification.DailyNotificationService
</code>

**Comment by chrislim** [comment]
It looks like it is successfully updating the existing intent. So would this mean the issue lies with the repeating interval on the alarm manager?

**Comment by chrislim** [comment]
We are only showing the notification when the service is created. I think we're supposed to send the service a message instead. The service could also be getting killed and recreated for memory reasons, which is why multiple notifications may be appearing.

See http://developer.android.com/reference/android/app/Service.html#WhatIsAService

**Comment by chrislim** [comment]
resolved in b2d6062
going to create another ticket for requesting permissions
