### ISSUE TITLE
Include page indicator on view pager based view for daily prayer experience

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#22]
In the iOS app we have a few dots at the bottom and one that is hightlighted for the page you are on. We need something like that in the Android app when users are in that mode.

**Comment by calvinf** [comment]
Android seems to use tabs along the top.  I think it would be good to use that pattern.  The problem with dots at the bottom is that it limits the view height and doesn't allow scrolling down to see additional content (without boxing the additional content into a smaller frame with a scrollbar which makes it harder to see everything).

I'm not sure if this is a bug, but we can look into addressing before app store launch.

**Comment by uberx** [comment]
The dots can take a small portion of the view at the bottom. It can go below the ViewPager and the ViewPager can scroll. It can be similar to how most of the Android home screens function.

**Comment by uberx** [comment]
And yeah, this might not be a bug, more like a feature.

**Comment by chrislim** [comment]
Users don't realize they can swipe through though, which is a ui nav bug. Even with the viewpagee they might not know to swipe (based on user feedback im getting)

**Comment by calvinf** [comment]
Tour could help but it's good to find an intuitive pattern. I'll keep
thinking about it.

**Comment by uberx** [comment]
I pushed out a fix for this - https://github.com/ceaseless-prayer/CeaselessAndroid/commit/75f78ae54f4cdb785e45afa11c3213542be57764

Please give it a try and let me know what you think.

**Comment by uberx** [comment]
The indicator seems to look satisfactory for now apart from some minor tweaks to the colors. Closing.
