### ISSUE TITLE
As a user I want to take notes about a person so that I remember how to pray for them

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#3]
The note is text-only, I should be able to create it from viewing the person or from a prayer journal where I can tag multiple people on a note.

**Comment by calvinf** [comment]
Would it be useful to add Markdown support in the future?  Certainly not required at the start, but it could be a nice touch down the road.

**Comment by chrislim** [comment]
Just downloaded the latest commit on this...should i expect to be able to tap "OK" and have it save?

**Comment by uberx** [comment]
I haven't wired up the CANCEL and OK buttons yet. I was too tired to do it last night. That part is pretty simple, I'll have it out tonight. The tricky part is going back to the right item in the view pager when CANCEL, OK, or the back button is hit. I was having a lot of trouble getting that to work last night.

**Comment by uberx** [comment]
I might have a way to get that to work for the OK and CANCEL buttons, but the back button is a lot more trickier because the MainActivity intercepts it right now. One way to get around this could be to just disable to back button in the AddNote view.

**Comment by chrislim** [comment]
Let's change OK to SAVE. If we need to disable the back button for now, it's okay.
Also instead of note title, it should be "Tag friends" or "Tag people".

**Comment by uberx** [comment]
I'll change OK to SAVE and disable to back button for now.

And oh, that's not the note title? I went off of page 11 from https://drive.google.com/file/d/0B4XNG8QPcv9xTDdlMVQ4czltWk0/view

**Comment by chrislim** [comment]
Yea, it's not Note Title, the design doc was not updated, but tagging people was the feature instead of Note Title. 
![image](https://cloud.githubusercontent.com/assets/469630/10530625/64970924-735e-11e5-84b2-0a0a3380fb02.png)

Here is the app preview video for iOS to see what the iOS version turned out to be like (30seconds) https://www.youtube.com/watch?v=BHh_eUjb3ew

**Comment by uberx** [comment]
Done - https://github.com/ceaseless-prayer/CeaselessAndroid/commit/8b76ea4917b4b8b2fc25b883e5c86b951cf2948c
