### ISSUE TITLE
The branding/look and feel of the app should be consistent

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#39]
Make sure we use a consistent color scheme, font size, font color, padding, border radius, etc. throughout the app.

**Comment by calvinf** [comment]
## Acceptance criteria

* Identify files containing font styling
* Identify files containing color styling
* Identify files containing border styling
* List this stuff in a wiki
* Review current values
* Propose revised values (send a pull request!)
* Document revisions
* Document color palette

## Comments and questions

Starting to take a look at this.

One of the main things I'm noticing is that the app feels very dark -- particularly the top bar, and the nav tray (background color for Ceaseless logo).

Current value: `#FF00012F`

Chris, how much are you willing to tweak the colors?  Do you have any specific brand colors you want to stick to?

**Comment by chrislim** [comment]
I'm working off of the design document. 00012f background + fff text are the two colors I'd like to stick to, but the opacity can be played with. If you'd like to mockup a few different color schemes, I'd like to look at them. The default would be to match the iOS app's scheme. Thanks!
