### ISSUE TITLE
As a user I want to review all my notes in the journal view so I remember God's grace

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#4]
The user should be able to see their notes listed by date and search through them, both by text and by people tagged in the note. The search should be a simple search bar.

**Comment by uberx** [comment]
This is essentially the Prayer Journal view, right?

**Comment by chrislim** [comment]
This is basically the prayer journal view. Users need to be able to create a new note from this view in addition to searching/viewing old notes and editing them.

**Comment by uberx** [comment]
I was wondering if we should separate the search out of this one. Looks like https://github.com/ceaseless-prayer/CeaselessAndroid/issues/40 includes search for notes and people.

**Comment by chrislim** [comment]
Sure we can make it part of the other ticket.



—

**Comment by chrislim** [comment]
Features for this view in alpha:
1. View notes in order by date
2. Edit notes
3. Delete notes
4. Create a new note

I'm trying to get the basic list going right now.

**Comment by chrislim** [comment]
The 67b3bd4 and the previous commit solves this although the formatting/layout could be nicer.
