### ISSUE TITLE
Get more profile images when available

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#47]
I have a contact for @ajma but in my phone I see the placeholder image. However when I load up the contact in the native app, he has a profile picture. We should be able to get that image and show it in the app.

**Comment by chrislim** [comment]
Weird, I just ran it again and this time an image did appear...

**Comment by chrislim** [comment]
It seems like it could be a caching issue. When I see a contact it frequently has only the placeholder. When I load the contact with the QuickContact view, it shows an image. When I load the app again the image then appears...I've seen this happen with a second contact.

**Comment by ajma** [comment]
... soooo.. did you pray for me? ;)

**Comment by chrislim** [comment]
Just did this morning :)

**Comment by chrislim** [comment]
Fixed in da68db2
