### ISSUE TITLE
As a user I want to favorite people who are the most significant to me so that I pray for them more often

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#5]
I can favorite or unfavorite a person when I see their card or when I look them up in the people directory.

**Comment by chrislim** [comment]
Favorited people should be selected for prayer more often. If you have less than 10 people favorited, let them show up 1/5 of the time. If you have more than 10 people favorited, then show one person each day. Select a person based on the one who was prayed for the longest time ago.

**Comment by calvinf** [comment]
I'll start working on designs for this soon.

**Comment by chrislim** [comment]
This is implemented in the algorithm, but we need to implement favoriting on the daily cards.

**Comment by chrislim** [comment]
Resolved in f23acd6
