### ISSUE TITLE
App crashes when I add a note

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#58]
This may be related to the parent view change that was recently made.
<pre>
FATAL EXCEPTION: main
11-10 11:23:21.437 21935-21935/org.theotech.ceaselessandroid E/AndroidRuntime: Process: org.theotech.ceaselessandroid, PID: 21935
11-10 11:23:21.437 21935-21935/org.theotech.ceaselessandroid E/AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
11-10 11:23:21.437 21935-21935/org.theotech.ceaselessandroid E/AndroidRuntime:     at android.view.ViewGroup.addViewInner(ViewGroup.java:3938)
11-10 11:23:21.437 21935-21935/org.theotech.ceaselessandroid E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3788)
11-10 11:23:21.437 21935-21935/org.theotech.ceaselessandroid E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3729)
11-10 11:23:21.437 21935-21935/org.theotech.ceaselessandroid E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3702)
11-10 11:23:21.437 21935-21935/org.theotech.ceaselessandroid E/AndroidRuntime:     at org.theotech.ceaselessandroid.util.CommonUtils.injectPersonIntoView(CommonUtils.
</pre>

**Comment by ceasingone** [comment]
You cut off the important part...could I get the line number in CommonUtils?

**Comment by ceasingone** [comment]
(Also, I'm not seeing the problem on my local build...odd)

**Comment by chrislim** [comment]
<pre>
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime: FATAL EXCEPTION: main
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime: Process: org.theotech.ceaselessandroid, PID: 27797
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.addViewInner(ViewGroup.java:3938)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3788)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3729)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3702)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at org.theotech.ceaselessandroid.util.CommonUtils.injectPersonIntoView(CommonUtils.java:83)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at org.theotech.ceaselessandroid.fragment.PersonSupportFragment.onCreateView(PersonSupportFragment.java:80)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:875)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.View.measure(View.java:17565)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2045)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1196)
11-10 11:44:46.248 27797-27797/? E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1409)
</pre>

**Comment by ceasingone** [comment]
#60 fixes it
