### ISSUE TITLE
Notifications are off by default even though the switch shows on

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#59]
We need to set the preference to true by default.

**Comment by chrislim** [comment]
Most recent run seemed to have these installed...going to double check.

**Comment by uberx** [comment]
Were you able to confirm if this is fixed?

**Comment by chrislim** [comment]
Not sure, but I think the problem mainly arises when we do a fresh install of the app.

**Comment by chrislim** [comment]
I think this is fixed in recent commit where we change default value to true when loading and no preferences have been set. It was set to false before.
