### ISSUE TITLE
As a user I want to manage the list of people I pray for so that I keep the list relevant and missional

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#6]
We don't want people to flip the app so that they only pray for their family, but we do want to make it easy for them to bulk select a bunch of random contacts and remove them from ceaseless. They should easily be able to favorite contacts and tap on a contact to view notes about that contact or reach out to them, etc. 

They should be able to edit the contact with the native contact editor as well.

**Comment by uberx** [comment]
Addressed by https://github.com/ceaseless-prayer/CeaselessAndroid/commit/9b9a8a127aaeadae386583a932770245b9132a0a

**Comment by uberx** [comment]
And https://github.com/ceaseless-prayer/CeaselessAndroid/commit/7530477a1cf4bf9c4541f72e4c900f0eb6bf589b
