### ISSUE TITLE
As a user I want to message people so that I can know how to pray for them

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#7]
Make it easy for a user to use native messaging capabilities to reach out to the contacts they pray for.

**Comment by chrislim** [comment]
Email and text are okay to start with.

**Comment by calvinf** [comment]
Do you want to be able to trigger this from the People view?  Anywhere else?

**Comment by chrislim** [comment]
Anytime you are viewing a person, whether it be due to the daily experience or due to browsing people you are praying for in general. The iOS app has the send message option in that person card everywhere it is used.

**Comment by chrislim** [comment]
Commit c12de57 adds this capability.
