### ISSUE TITLE
When the user finishes praying for friends, they can't continue

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#78]
Feedback from a user when they reach the end of their contacts:

It seems to be stuck. When I click show more it just shows one more and still two not implemented yet cards. My progress shows I am still missing one person.
![screenshot_2016-05-12-20-51-41](https://cloud.githubusercontent.com/assets/469630/15262259/066125b6-1916-11e6-923c-0c9d5371b853.png)
![screenshot_2016-05-12-20-49-30](https://cloud.githubusercontent.com/assets/469630/15262260/09a67e10-1916-11e6-86e9-e8cd694a3bb6.png)

**Comment by chrislim** [comment]
I think we may want to change the logic here: https://github.com/ceaseless-prayer/CeaselessAndroid/blob/master/app/src/main/java/org/theotech/ceaselessandroid/person/PersonManagerImpl.java#L146

**Comment by uberx** [comment]
Fixed by https://github.com/ceaseless-prayer/CeaselessAndroid/commit/82629fe635f815fa34f21c0e05f530467ae5b1f0
