### ISSUE TITLE
Tutorial Fix: Modify "swipe to start praying" step

### ISSUE THREAD

**Issue by nylim11** [ceaseless-prayer/CeaselessAndroid#84]
Currently, users are getting confused on the "swipe to start praying" step of the tutorial. With the arrow pointing to the right, they think to tap on the arrow rather than swipe.

Possible fixes: 
1. Animate arrow to point in the direction of the swipe (from right to left)
2. Make the arrow tappable, so when a user taps on it, Ceaseless automatically swipes to the next card 
3. Make the arrow tappable, so when a user taps on it, the next card "bumps" in, indicating the next piece of content but not performing the swipe for them.
4. Other ?

**Comment by nylim11** [comment]
Need to re-examine the onboarding experience to see what other improvements need to be made

**Comment by chrislim** [comment]
Should we keep the tutorial or maybe add an initial step where they can start or skip it?

**Comment by chrislim** [comment]
The arrow points to the left now to resolve the confusion. The onboarding could be significantly improved still, but this issue is resolved.
